/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminAuthRouteImport } from './routes/_adminAuth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuthAdminIndexRouteImport } from './routes/_adminAuth.admin.index'
import { Route as AdminAuthAdminStaffRouteImport } from './routes/_adminAuth.admin.staff'
import { Route as AdminAuthAdminSettingsRouteImport } from './routes/_adminAuth.admin.settings'
import { Route as AdminAuthAdminProductsRouteImport } from './routes/_adminAuth.admin.products'
import { Route as AdminAuthAdminEnquiriesRouteImport } from './routes/_adminAuth.admin.enquiries'
import { Route as AdminAuthAdminDashboardRouteImport } from './routes/_adminAuth.admin.dashboard'
import { Route as AdminAuthAdminBlogsRouteImport } from './routes/_adminAuth.admin.blogs'
import { Route as AdminAuthAdminAnalyticsRouteImport } from './routes/_adminAuth.admin.analytics'
import { Route as AdminAuthAdminProductsNewRouteImport } from './routes/_adminAuth.admin.products_.new'
import { Route as AdminAuthAdminProductsIdRouteImport } from './routes/_adminAuth.admin.products.$id'
import { Route as AdminAuthAdminEnquiriesNewRouteImport } from './routes/_adminAuth.admin.enquiries.new'
import { Route as AdminAuthAdminEnquiriesIdRouteImport } from './routes/_adminAuth.admin.enquiries.$id'
import { Route as AdminAuthAdminBlogsNewRouteImport } from './routes/_adminAuth.admin.blogs.new'
import { Route as AdminAuthAdminBlogsIdRouteImport } from './routes/_adminAuth.admin.blogs.$id'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/_adminAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthAdminIndexRoute = AdminAuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminStaffRoute = AdminAuthAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminSettingsRoute = AdminAuthAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminProductsRoute = AdminAuthAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminEnquiriesRoute = AdminAuthAdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminDashboardRoute = AdminAuthAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminBlogsRoute = AdminAuthAdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminAnalyticsRoute = AdminAuthAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminProductsNewRoute =
  AdminAuthAdminProductsNewRouteImport.update({
    id: '/admin/products_/new',
    path: '/admin/products/new',
    getParentRoute: () => AdminAuthRoute,
  } as any)
const AdminAuthAdminProductsIdRoute =
  AdminAuthAdminProductsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAuthAdminProductsRoute,
  } as any)
const AdminAuthAdminEnquiriesNewRoute =
  AdminAuthAdminEnquiriesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAuthAdminEnquiriesRoute,
  } as any)
const AdminAuthAdminEnquiriesIdRoute =
  AdminAuthAdminEnquiriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAuthAdminEnquiriesRoute,
  } as any)
const AdminAuthAdminBlogsNewRoute = AdminAuthAdminBlogsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminAuthAdminBlogsRoute,
} as any)
const AdminAuthAdminBlogsIdRoute = AdminAuthAdminBlogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAuthAdminBlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/analytics': typeof AdminAuthAdminAnalyticsRoute
  '/admin/blogs': typeof AdminAuthAdminBlogsRouteWithChildren
  '/admin/dashboard': typeof AdminAuthAdminDashboardRoute
  '/admin/enquiries': typeof AdminAuthAdminEnquiriesRouteWithChildren
  '/admin/products': typeof AdminAuthAdminProductsRouteWithChildren
  '/admin/settings': typeof AdminAuthAdminSettingsRoute
  '/admin/staff': typeof AdminAuthAdminStaffRoute
  '/admin/': typeof AdminAuthAdminIndexRoute
  '/admin/blogs/$id': typeof AdminAuthAdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminAuthAdminBlogsNewRoute
  '/admin/enquiries/$id': typeof AdminAuthAdminEnquiriesIdRoute
  '/admin/enquiries/new': typeof AdminAuthAdminEnquiriesNewRoute
  '/admin/products/$id': typeof AdminAuthAdminProductsIdRoute
  '/admin/products/new': typeof AdminAuthAdminProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/admin/analytics': typeof AdminAuthAdminAnalyticsRoute
  '/admin/blogs': typeof AdminAuthAdminBlogsRouteWithChildren
  '/admin/dashboard': typeof AdminAuthAdminDashboardRoute
  '/admin/enquiries': typeof AdminAuthAdminEnquiriesRouteWithChildren
  '/admin/products': typeof AdminAuthAdminProductsRouteWithChildren
  '/admin/settings': typeof AdminAuthAdminSettingsRoute
  '/admin/staff': typeof AdminAuthAdminStaffRoute
  '/admin': typeof AdminAuthAdminIndexRoute
  '/admin/blogs/$id': typeof AdminAuthAdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminAuthAdminBlogsNewRoute
  '/admin/enquiries/$id': typeof AdminAuthAdminEnquiriesIdRoute
  '/admin/enquiries/new': typeof AdminAuthAdminEnquiriesNewRoute
  '/admin/products/$id': typeof AdminAuthAdminProductsIdRoute
  '/admin/products/new': typeof AdminAuthAdminProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_adminAuth': typeof AdminAuthRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_adminAuth/admin/analytics': typeof AdminAuthAdminAnalyticsRoute
  '/_adminAuth/admin/blogs': typeof AdminAuthAdminBlogsRouteWithChildren
  '/_adminAuth/admin/dashboard': typeof AdminAuthAdminDashboardRoute
  '/_adminAuth/admin/enquiries': typeof AdminAuthAdminEnquiriesRouteWithChildren
  '/_adminAuth/admin/products': typeof AdminAuthAdminProductsRouteWithChildren
  '/_adminAuth/admin/settings': typeof AdminAuthAdminSettingsRoute
  '/_adminAuth/admin/staff': typeof AdminAuthAdminStaffRoute
  '/_adminAuth/admin/': typeof AdminAuthAdminIndexRoute
  '/_adminAuth/admin/blogs/$id': typeof AdminAuthAdminBlogsIdRoute
  '/_adminAuth/admin/blogs/new': typeof AdminAuthAdminBlogsNewRoute
  '/_adminAuth/admin/enquiries/$id': typeof AdminAuthAdminEnquiriesIdRoute
  '/_adminAuth/admin/enquiries/new': typeof AdminAuthAdminEnquiriesNewRoute
  '/_adminAuth/admin/products/$id': typeof AdminAuthAdminProductsIdRoute
  '/_adminAuth/admin/products_/new': typeof AdminAuthAdminProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/login'
    | '/products'
    | '/admin/login'
    | '/blog/$slug'
    | '/products/$slug'
    | '/blog/'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/enquiries/$id'
    | '/admin/enquiries/new'
    | '/admin/products/$id'
    | '/admin/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/login'
    | '/products'
    | '/admin/login'
    | '/blog/$slug'
    | '/products/$slug'
    | '/blog'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/enquiries/$id'
    | '/admin/enquiries/new'
    | '/admin/products/$id'
    | '/admin/products/new'
  id:
    | '__root__'
    | '/'
    | '/_adminAuth'
    | '/about'
    | '/contact'
    | '/industries'
    | '/login'
    | '/products'
    | '/admin/login'
    | '/blog/$slug'
    | '/products/$slug'
    | '/blog/'
    | '/_adminAuth/admin/analytics'
    | '/_adminAuth/admin/blogs'
    | '/_adminAuth/admin/dashboard'
    | '/_adminAuth/admin/enquiries'
    | '/_adminAuth/admin/products'
    | '/_adminAuth/admin/settings'
    | '/_adminAuth/admin/staff'
    | '/_adminAuth/admin/'
    | '/_adminAuth/admin/blogs/$id'
    | '/_adminAuth/admin/blogs/new'
    | '/_adminAuth/admin/enquiries/$id'
    | '/_adminAuth/admin/enquiries/new'
    | '/_adminAuth/admin/products/$id'
    | '/_adminAuth/admin/products_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminAuth': {
      id: '/_adminAuth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminAuth/admin/': {
      id: '/_adminAuth/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthAdminIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/staff': {
      id: '/_adminAuth/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminAuthAdminStaffRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/settings': {
      id: '/_adminAuth/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthAdminSettingsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/products': {
      id: '/_adminAuth/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAuthAdminProductsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/enquiries': {
      id: '/_adminAuth/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminAuthAdminEnquiriesRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/dashboard': {
      id: '/_adminAuth/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthAdminDashboardRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/blogs': {
      id: '/_adminAuth/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminAuthAdminBlogsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/analytics': {
      id: '/_adminAuth/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAuthAdminAnalyticsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/products_/new': {
      id: '/_adminAuth/admin/products_/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminAuthAdminProductsNewRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/products/$id': {
      id: '/_adminAuth/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminAuthAdminProductsIdRouteImport
      parentRoute: typeof AdminAuthAdminProductsRoute
    }
    '/_adminAuth/admin/enquiries/new': {
      id: '/_adminAuth/admin/enquiries/new'
      path: '/new'
      fullPath: '/admin/enquiries/new'
      preLoaderRoute: typeof AdminAuthAdminEnquiriesNewRouteImport
      parentRoute: typeof AdminAuthAdminEnquiriesRoute
    }
    '/_adminAuth/admin/enquiries/$id': {
      id: '/_adminAuth/admin/enquiries/$id'
      path: '/$id'
      fullPath: '/admin/enquiries/$id'
      preLoaderRoute: typeof AdminAuthAdminEnquiriesIdRouteImport
      parentRoute: typeof AdminAuthAdminEnquiriesRoute
    }
    '/_adminAuth/admin/blogs/new': {
      id: '/_adminAuth/admin/blogs/new'
      path: '/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminAuthAdminBlogsNewRouteImport
      parentRoute: typeof AdminAuthAdminBlogsRoute
    }
    '/_adminAuth/admin/blogs/$id': {
      id: '/_adminAuth/admin/blogs/$id'
      path: '/$id'
      fullPath: '/admin/blogs/$id'
      preLoaderRoute: typeof AdminAuthAdminBlogsIdRouteImport
      parentRoute: typeof AdminAuthAdminBlogsRoute
    }
  }
}

interface AdminAuthAdminBlogsRouteChildren {
  AdminAuthAdminBlogsIdRoute: typeof AdminAuthAdminBlogsIdRoute
  AdminAuthAdminBlogsNewRoute: typeof AdminAuthAdminBlogsNewRoute
}

const AdminAuthAdminBlogsRouteChildren: AdminAuthAdminBlogsRouteChildren = {
  AdminAuthAdminBlogsIdRoute: AdminAuthAdminBlogsIdRoute,
  AdminAuthAdminBlogsNewRoute: AdminAuthAdminBlogsNewRoute,
}

const AdminAuthAdminBlogsRouteWithChildren =
  AdminAuthAdminBlogsRoute._addFileChildren(AdminAuthAdminBlogsRouteChildren)

interface AdminAuthAdminEnquiriesRouteChildren {
  AdminAuthAdminEnquiriesIdRoute: typeof AdminAuthAdminEnquiriesIdRoute
  AdminAuthAdminEnquiriesNewRoute: typeof AdminAuthAdminEnquiriesNewRoute
}

const AdminAuthAdminEnquiriesRouteChildren: AdminAuthAdminEnquiriesRouteChildren =
  {
    AdminAuthAdminEnquiriesIdRoute: AdminAuthAdminEnquiriesIdRoute,
    AdminAuthAdminEnquiriesNewRoute: AdminAuthAdminEnquiriesNewRoute,
  }

const AdminAuthAdminEnquiriesRouteWithChildren =
  AdminAuthAdminEnquiriesRoute._addFileChildren(
    AdminAuthAdminEnquiriesRouteChildren,
  )

interface AdminAuthAdminProductsRouteChildren {
  AdminAuthAdminProductsIdRoute: typeof AdminAuthAdminProductsIdRoute
}

const AdminAuthAdminProductsRouteChildren: AdminAuthAdminProductsRouteChildren =
  {
    AdminAuthAdminProductsIdRoute: AdminAuthAdminProductsIdRoute,
  }

const AdminAuthAdminProductsRouteWithChildren =
  AdminAuthAdminProductsRoute._addFileChildren(
    AdminAuthAdminProductsRouteChildren,
  )

interface AdminAuthRouteChildren {
  AdminAuthAdminAnalyticsRoute: typeof AdminAuthAdminAnalyticsRoute
  AdminAuthAdminBlogsRoute: typeof AdminAuthAdminBlogsRouteWithChildren
  AdminAuthAdminDashboardRoute: typeof AdminAuthAdminDashboardRoute
  AdminAuthAdminEnquiriesRoute: typeof AdminAuthAdminEnquiriesRouteWithChildren
  AdminAuthAdminProductsRoute: typeof AdminAuthAdminProductsRouteWithChildren
  AdminAuthAdminSettingsRoute: typeof AdminAuthAdminSettingsRoute
  AdminAuthAdminStaffRoute: typeof AdminAuthAdminStaffRoute
  AdminAuthAdminIndexRoute: typeof AdminAuthAdminIndexRoute
  AdminAuthAdminProductsNewRoute: typeof AdminAuthAdminProductsNewRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthAdminAnalyticsRoute: AdminAuthAdminAnalyticsRoute,
  AdminAuthAdminBlogsRoute: AdminAuthAdminBlogsRouteWithChildren,
  AdminAuthAdminDashboardRoute: AdminAuthAdminDashboardRoute,
  AdminAuthAdminEnquiriesRoute: AdminAuthAdminEnquiriesRouteWithChildren,
  AdminAuthAdminProductsRoute: AdminAuthAdminProductsRouteWithChildren,
  AdminAuthAdminSettingsRoute: AdminAuthAdminSettingsRoute,
  AdminAuthAdminStaffRoute: AdminAuthAdminStaffRoute,
  AdminAuthAdminIndexRoute: AdminAuthAdminIndexRoute,
  AdminAuthAdminProductsNewRoute: AdminAuthAdminProductsNewRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
