/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as EnterpriseQuoteRouteImport } from './routes/enterprise-quote'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminAuthRouteImport } from './routes/_adminAuth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as OrdersTrackRouteImport } from './routes/orders.track'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutProcessingRouteImport } from './routes/checkout.processing'
import { Route as CheckoutFailedRouteImport } from './routes/checkout.failed'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountVerifyRouteImport } from './routes/account.verify'
import { Route as AccountResetPasswordRouteImport } from './routes/account.reset-password'
import { Route as AccountRegisterRouteImport } from './routes/account.register'
import { Route as AccountReferralsRouteImport } from './routes/account.referrals'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AccountForgotPasswordRouteImport } from './routes/account.forgot-password'
import { Route as AccountDashboardRouteImport } from './routes/account.dashboard'
import { Route as AdminAuthAdminIndexRouteImport } from './routes/_adminAuth.admin.index'
import { Route as AccountOrdersReferenceRouteImport } from './routes/account.orders.$reference'
import { Route as AdminAuthAdminUsersRouteImport } from './routes/_adminAuth.admin.users'
import { Route as AdminAuthAdminStaffRouteImport } from './routes/_adminAuth.admin.staff'
import { Route as AdminAuthAdminSettingsRouteImport } from './routes/_adminAuth.admin.settings'
import { Route as AdminAuthAdminReviewsRouteImport } from './routes/_adminAuth.admin.reviews'
import { Route as AdminAuthAdminPaymentsRouteImport } from './routes/_adminAuth.admin.payments'
import { Route as AdminAuthAdminOrdersRouteImport } from './routes/_adminAuth.admin.orders'
import { Route as AdminAuthAdminIndustriesRouteImport } from './routes/_adminAuth.admin.industries'
import { Route as AdminAuthAdminEnquiriesRouteImport } from './routes/_adminAuth.admin.enquiries'
import { Route as AdminAuthAdminDeliveryZonesRouteImport } from './routes/_adminAuth.admin.delivery-zones'
import { Route as AdminAuthAdminDashboardRouteImport } from './routes/_adminAuth.admin.dashboard'
import { Route as AdminAuthAdminCustomersRouteImport } from './routes/_adminAuth.admin.customers'
import { Route as AdminAuthAdminBlogsRouteImport } from './routes/_adminAuth.admin.blogs'
import { Route as AdminAuthAdminAnalyticsRouteImport } from './routes/_adminAuth.admin.analytics'
import { Route as AdminAuthAdminProductsIndexRouteImport } from './routes/_adminAuth.admin.products.index'
import { Route as AdminAuthAdminProductsNewRouteImport } from './routes/_adminAuth.admin.products_.new'
import { Route as AdminAuthAdminProductsIdRouteImport } from './routes/_adminAuth.admin.products.$id'
import { Route as AdminAuthAdminOrdersIdRouteImport } from './routes/_adminAuth.admin.orders.$id'
import { Route as AdminAuthAdminEnquiriesNewRouteImport } from './routes/_adminAuth.admin.enquiries.new'
import { Route as AdminAuthAdminEnquiriesIdRouteImport } from './routes/_adminAuth.admin.enquiries.$id'
import { Route as AdminAuthAdminCustomersIdRouteImport } from './routes/_adminAuth.admin.customers.$id'
import { Route as AdminAuthAdminBlogsNewRouteImport } from './routes/_adminAuth.admin.blogs.new'
import { Route as AdminAuthAdminBlogsIdRouteImport } from './routes/_adminAuth.admin.blogs.$id'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseQuoteRoute = EnterpriseQuoteRouteImport.update({
  id: '/enterprise-quote',
  path: '/enterprise-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/_adminAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const OrdersTrackRoute = OrdersTrackRouteImport.update({
  id: '/orders/track',
  path: '/orders/track',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutProcessingRoute = CheckoutProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutFailedRoute = CheckoutFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => CheckoutRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/account/wishlist',
  path: '/account/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyRoute = AccountVerifyRouteImport.update({
  id: '/account/verify',
  path: '/account/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReferralsRoute = AccountReferralsRouteImport.update({
  id: '/account/referrals',
  path: '/account/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/account/forgot-password',
  path: '/account/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDashboardRoute = AccountDashboardRouteImport.update({
  id: '/account/dashboard',
  path: '/account/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthAdminIndexRoute = AdminAuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AccountOrdersReferenceRoute = AccountOrdersReferenceRouteImport.update({
  id: '/$reference',
  path: '/$reference',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AdminAuthAdminUsersRoute = AdminAuthAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminStaffRoute = AdminAuthAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminSettingsRoute = AdminAuthAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminReviewsRoute = AdminAuthAdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminPaymentsRoute = AdminAuthAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminOrdersRoute = AdminAuthAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminIndustriesRoute =
  AdminAuthAdminIndustriesRouteImport.update({
    id: '/admin/industries',
    path: '/admin/industries',
    getParentRoute: () => AdminAuthRoute,
  } as any)
const AdminAuthAdminEnquiriesRoute = AdminAuthAdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminDeliveryZonesRoute =
  AdminAuthAdminDeliveryZonesRouteImport.update({
    id: '/admin/delivery-zones',
    path: '/admin/delivery-zones',
    getParentRoute: () => AdminAuthRoute,
  } as any)
const AdminAuthAdminDashboardRoute = AdminAuthAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminCustomersRoute = AdminAuthAdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminBlogsRoute = AdminAuthAdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminAnalyticsRoute = AdminAuthAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminProductsIndexRoute =
  AdminAuthAdminProductsIndexRouteImport.update({
    id: '/admin/products/',
    path: '/admin/products/',
    getParentRoute: () => AdminAuthRoute,
  } as any)
const AdminAuthAdminProductsNewRoute =
  AdminAuthAdminProductsNewRouteImport.update({
    id: '/admin/products_/new',
    path: '/admin/products/new',
    getParentRoute: () => AdminAuthRoute,
  } as any)
const AdminAuthAdminProductsIdRoute =
  AdminAuthAdminProductsIdRouteImport.update({
    id: '/admin/products/$id',
    path: '/admin/products/$id',
    getParentRoute: () => AdminAuthRoute,
  } as any)
const AdminAuthAdminOrdersIdRoute = AdminAuthAdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAuthAdminOrdersRoute,
} as any)
const AdminAuthAdminEnquiriesNewRoute =
  AdminAuthAdminEnquiriesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAuthAdminEnquiriesRoute,
  } as any)
const AdminAuthAdminEnquiriesIdRoute =
  AdminAuthAdminEnquiriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAuthAdminEnquiriesRoute,
  } as any)
const AdminAuthAdminCustomersIdRoute =
  AdminAuthAdminCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAuthAdminCustomersRoute,
  } as any)
const AdminAuthAdminBlogsNewRoute = AdminAuthAdminBlogsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminAuthAdminBlogsRoute,
} as any)
const AdminAuthAdminBlogsIdRoute = AdminAuthAdminBlogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAuthAdminBlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/enterprise-quote': typeof EnterpriseQuoteRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/products': typeof ProductsRouteWithChildren
  '/staff': typeof StaffRoute
  '/account/dashboard': typeof AccountDashboardRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/referrals': typeof AccountReferralsRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/verify': typeof AccountVerifyRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/processing': typeof CheckoutProcessingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/orders/track': typeof OrdersTrackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/analytics': typeof AdminAuthAdminAnalyticsRoute
  '/admin/blogs': typeof AdminAuthAdminBlogsRouteWithChildren
  '/admin/customers': typeof AdminAuthAdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminAuthAdminDashboardRoute
  '/admin/delivery-zones': typeof AdminAuthAdminDeliveryZonesRoute
  '/admin/enquiries': typeof AdminAuthAdminEnquiriesRouteWithChildren
  '/admin/industries': typeof AdminAuthAdminIndustriesRoute
  '/admin/orders': typeof AdminAuthAdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminAuthAdminPaymentsRoute
  '/admin/reviews': typeof AdminAuthAdminReviewsRoute
  '/admin/settings': typeof AdminAuthAdminSettingsRoute
  '/admin/staff': typeof AdminAuthAdminStaffRoute
  '/admin/users': typeof AdminAuthAdminUsersRoute
  '/account/orders/$reference': typeof AccountOrdersReferenceRoute
  '/admin/': typeof AdminAuthAdminIndexRoute
  '/admin/blogs/$id': typeof AdminAuthAdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminAuthAdminBlogsNewRoute
  '/admin/customers/$id': typeof AdminAuthAdminCustomersIdRoute
  '/admin/enquiries/$id': typeof AdminAuthAdminEnquiriesIdRoute
  '/admin/enquiries/new': typeof AdminAuthAdminEnquiriesNewRoute
  '/admin/orders/$id': typeof AdminAuthAdminOrdersIdRoute
  '/admin/products/$id': typeof AdminAuthAdminProductsIdRoute
  '/admin/products/new': typeof AdminAuthAdminProductsNewRoute
  '/admin/products/': typeof AdminAuthAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/enterprise-quote': typeof EnterpriseQuoteRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/products': typeof ProductsRouteWithChildren
  '/staff': typeof StaffRoute
  '/account/dashboard': typeof AccountDashboardRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/referrals': typeof AccountReferralsRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/verify': typeof AccountVerifyRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/processing': typeof CheckoutProcessingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/orders/track': typeof OrdersTrackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/admin/analytics': typeof AdminAuthAdminAnalyticsRoute
  '/admin/blogs': typeof AdminAuthAdminBlogsRouteWithChildren
  '/admin/customers': typeof AdminAuthAdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminAuthAdminDashboardRoute
  '/admin/delivery-zones': typeof AdminAuthAdminDeliveryZonesRoute
  '/admin/enquiries': typeof AdminAuthAdminEnquiriesRouteWithChildren
  '/admin/industries': typeof AdminAuthAdminIndustriesRoute
  '/admin/orders': typeof AdminAuthAdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminAuthAdminPaymentsRoute
  '/admin/reviews': typeof AdminAuthAdminReviewsRoute
  '/admin/settings': typeof AdminAuthAdminSettingsRoute
  '/admin/staff': typeof AdminAuthAdminStaffRoute
  '/admin/users': typeof AdminAuthAdminUsersRoute
  '/account/orders/$reference': typeof AccountOrdersReferenceRoute
  '/admin': typeof AdminAuthAdminIndexRoute
  '/admin/blogs/$id': typeof AdminAuthAdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminAuthAdminBlogsNewRoute
  '/admin/customers/$id': typeof AdminAuthAdminCustomersIdRoute
  '/admin/enquiries/$id': typeof AdminAuthAdminEnquiriesIdRoute
  '/admin/enquiries/new': typeof AdminAuthAdminEnquiriesNewRoute
  '/admin/orders/$id': typeof AdminAuthAdminOrdersIdRoute
  '/admin/products/$id': typeof AdminAuthAdminProductsIdRoute
  '/admin/products/new': typeof AdminAuthAdminProductsNewRoute
  '/admin/products': typeof AdminAuthAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_adminAuth': typeof AdminAuthRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/enterprise-quote': typeof EnterpriseQuoteRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/products': typeof ProductsRouteWithChildren
  '/staff': typeof StaffRoute
  '/account/dashboard': typeof AccountDashboardRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/referrals': typeof AccountReferralsRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/verify': typeof AccountVerifyRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/processing': typeof CheckoutProcessingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/orders/track': typeof OrdersTrackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_adminAuth/admin/analytics': typeof AdminAuthAdminAnalyticsRoute
  '/_adminAuth/admin/blogs': typeof AdminAuthAdminBlogsRouteWithChildren
  '/_adminAuth/admin/customers': typeof AdminAuthAdminCustomersRouteWithChildren
  '/_adminAuth/admin/dashboard': typeof AdminAuthAdminDashboardRoute
  '/_adminAuth/admin/delivery-zones': typeof AdminAuthAdminDeliveryZonesRoute
  '/_adminAuth/admin/enquiries': typeof AdminAuthAdminEnquiriesRouteWithChildren
  '/_adminAuth/admin/industries': typeof AdminAuthAdminIndustriesRoute
  '/_adminAuth/admin/orders': typeof AdminAuthAdminOrdersRouteWithChildren
  '/_adminAuth/admin/payments': typeof AdminAuthAdminPaymentsRoute
  '/_adminAuth/admin/reviews': typeof AdminAuthAdminReviewsRoute
  '/_adminAuth/admin/settings': typeof AdminAuthAdminSettingsRoute
  '/_adminAuth/admin/staff': typeof AdminAuthAdminStaffRoute
  '/_adminAuth/admin/users': typeof AdminAuthAdminUsersRoute
  '/account/orders/$reference': typeof AccountOrdersReferenceRoute
  '/_adminAuth/admin/': typeof AdminAuthAdminIndexRoute
  '/_adminAuth/admin/blogs/$id': typeof AdminAuthAdminBlogsIdRoute
  '/_adminAuth/admin/blogs/new': typeof AdminAuthAdminBlogsNewRoute
  '/_adminAuth/admin/customers/$id': typeof AdminAuthAdminCustomersIdRoute
  '/_adminAuth/admin/enquiries/$id': typeof AdminAuthAdminEnquiriesIdRoute
  '/_adminAuth/admin/enquiries/new': typeof AdminAuthAdminEnquiriesNewRoute
  '/_adminAuth/admin/orders/$id': typeof AdminAuthAdminOrdersIdRoute
  '/_adminAuth/admin/products/$id': typeof AdminAuthAdminProductsIdRoute
  '/_adminAuth/admin/products_/new': typeof AdminAuthAdminProductsNewRoute
  '/_adminAuth/admin/products/': typeof AdminAuthAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/enterprise-quote'
    | '/industries'
    | '/login'
    | '/order-confirmation'
    | '/products'
    | '/staff'
    | '/account/dashboard'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/orders'
    | '/account/profile'
    | '/account/referrals'
    | '/account/register'
    | '/account/reset-password'
    | '/account/verify'
    | '/account/wishlist'
    | '/admin/login'
    | '/blog/$slug'
    | '/checkout/failed'
    | '/checkout/processing'
    | '/checkout/success'
    | '/orders/track'
    | '/products/$slug'
    | '/blog/'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery-zones'
    | '/admin/enquiries'
    | '/admin/industries'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/users'
    | '/account/orders/$reference'
    | '/admin/'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/customers/$id'
    | '/admin/enquiries/$id'
    | '/admin/enquiries/new'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/enterprise-quote'
    | '/industries'
    | '/login'
    | '/order-confirmation'
    | '/products'
    | '/staff'
    | '/account/dashboard'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/orders'
    | '/account/profile'
    | '/account/referrals'
    | '/account/register'
    | '/account/reset-password'
    | '/account/verify'
    | '/account/wishlist'
    | '/admin/login'
    | '/blog/$slug'
    | '/checkout/failed'
    | '/checkout/processing'
    | '/checkout/success'
    | '/orders/track'
    | '/products/$slug'
    | '/blog'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery-zones'
    | '/admin/enquiries'
    | '/admin/industries'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/users'
    | '/account/orders/$reference'
    | '/admin'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/customers/$id'
    | '/admin/enquiries/$id'
    | '/admin/enquiries/new'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/_adminAuth'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/enterprise-quote'
    | '/industries'
    | '/login'
    | '/order-confirmation'
    | '/products'
    | '/staff'
    | '/account/dashboard'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/orders'
    | '/account/profile'
    | '/account/referrals'
    | '/account/register'
    | '/account/reset-password'
    | '/account/verify'
    | '/account/wishlist'
    | '/admin/login'
    | '/blog/$slug'
    | '/checkout/failed'
    | '/checkout/processing'
    | '/checkout/success'
    | '/orders/track'
    | '/products/$slug'
    | '/blog/'
    | '/_adminAuth/admin/analytics'
    | '/_adminAuth/admin/blogs'
    | '/_adminAuth/admin/customers'
    | '/_adminAuth/admin/dashboard'
    | '/_adminAuth/admin/delivery-zones'
    | '/_adminAuth/admin/enquiries'
    | '/_adminAuth/admin/industries'
    | '/_adminAuth/admin/orders'
    | '/_adminAuth/admin/payments'
    | '/_adminAuth/admin/reviews'
    | '/_adminAuth/admin/settings'
    | '/_adminAuth/admin/staff'
    | '/_adminAuth/admin/users'
    | '/account/orders/$reference'
    | '/_adminAuth/admin/'
    | '/_adminAuth/admin/blogs/$id'
    | '/_adminAuth/admin/blogs/new'
    | '/_adminAuth/admin/customers/$id'
    | '/_adminAuth/admin/enquiries/$id'
    | '/_adminAuth/admin/enquiries/new'
    | '/_adminAuth/admin/orders/$id'
    | '/_adminAuth/admin/products/$id'
    | '/_adminAuth/admin/products_/new'
    | '/_adminAuth/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  EnterpriseQuoteRoute: typeof EnterpriseQuoteRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  StaffRoute: typeof StaffRoute
  AccountDashboardRoute: typeof AccountDashboardRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReferralsRoute: typeof AccountReferralsRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountVerifyRoute: typeof AccountVerifyRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  OrdersTrackRoute: typeof OrdersTrackRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-quote': {
      id: '/enterprise-quote'
      path: '/enterprise-quote'
      fullPath: '/enterprise-quote'
      preLoaderRoute: typeof EnterpriseQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminAuth': {
      id: '/_adminAuth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/orders/track': {
      id: '/orders/track'
      path: '/orders/track'
      fullPath: '/orders/track'
      preLoaderRoute: typeof OrdersTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/processing': {
      id: '/checkout/processing'
      path: '/processing'
      fullPath: '/checkout/processing'
      preLoaderRoute: typeof CheckoutProcessingRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/failed': {
      id: '/checkout/failed'
      path: '/failed'
      fullPath: '/checkout/failed'
      preLoaderRoute: typeof CheckoutFailedRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/account/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify': {
      id: '/account/verify'
      path: '/account/verify'
      fullPath: '/account/verify'
      preLoaderRoute: typeof AccountVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/referrals': {
      id: '/account/referrals'
      path: '/account/referrals'
      fullPath: '/account/referrals'
      preLoaderRoute: typeof AccountReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/dashboard': {
      id: '/account/dashboard'
      path: '/account/dashboard'
      fullPath: '/account/dashboard'
      preLoaderRoute: typeof AccountDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminAuth/admin/': {
      id: '/_adminAuth/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthAdminIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/account/orders/$reference': {
      id: '/account/orders/$reference'
      path: '/$reference'
      fullPath: '/account/orders/$reference'
      preLoaderRoute: typeof AccountOrdersReferenceRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/_adminAuth/admin/users': {
      id: '/_adminAuth/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAuthAdminUsersRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/staff': {
      id: '/_adminAuth/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminAuthAdminStaffRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/settings': {
      id: '/_adminAuth/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthAdminSettingsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/reviews': {
      id: '/_adminAuth/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminAuthAdminReviewsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/payments': {
      id: '/_adminAuth/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAuthAdminPaymentsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/orders': {
      id: '/_adminAuth/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAuthAdminOrdersRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/industries': {
      id: '/_adminAuth/admin/industries'
      path: '/admin/industries'
      fullPath: '/admin/industries'
      preLoaderRoute: typeof AdminAuthAdminIndustriesRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/enquiries': {
      id: '/_adminAuth/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminAuthAdminEnquiriesRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/delivery-zones': {
      id: '/_adminAuth/admin/delivery-zones'
      path: '/admin/delivery-zones'
      fullPath: '/admin/delivery-zones'
      preLoaderRoute: typeof AdminAuthAdminDeliveryZonesRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/dashboard': {
      id: '/_adminAuth/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthAdminDashboardRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/customers': {
      id: '/_adminAuth/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminAuthAdminCustomersRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/blogs': {
      id: '/_adminAuth/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminAuthAdminBlogsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/analytics': {
      id: '/_adminAuth/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAuthAdminAnalyticsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/products/': {
      id: '/_adminAuth/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminAuthAdminProductsIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/products_/new': {
      id: '/_adminAuth/admin/products_/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminAuthAdminProductsNewRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/products/$id': {
      id: '/_adminAuth/admin/products/$id'
      path: '/admin/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminAuthAdminProductsIdRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/orders/$id': {
      id: '/_adminAuth/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminAuthAdminOrdersIdRouteImport
      parentRoute: typeof AdminAuthAdminOrdersRoute
    }
    '/_adminAuth/admin/enquiries/new': {
      id: '/_adminAuth/admin/enquiries/new'
      path: '/new'
      fullPath: '/admin/enquiries/new'
      preLoaderRoute: typeof AdminAuthAdminEnquiriesNewRouteImport
      parentRoute: typeof AdminAuthAdminEnquiriesRoute
    }
    '/_adminAuth/admin/enquiries/$id': {
      id: '/_adminAuth/admin/enquiries/$id'
      path: '/$id'
      fullPath: '/admin/enquiries/$id'
      preLoaderRoute: typeof AdminAuthAdminEnquiriesIdRouteImport
      parentRoute: typeof AdminAuthAdminEnquiriesRoute
    }
    '/_adminAuth/admin/customers/$id': {
      id: '/_adminAuth/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminAuthAdminCustomersIdRouteImport
      parentRoute: typeof AdminAuthAdminCustomersRoute
    }
    '/_adminAuth/admin/blogs/new': {
      id: '/_adminAuth/admin/blogs/new'
      path: '/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminAuthAdminBlogsNewRouteImport
      parentRoute: typeof AdminAuthAdminBlogsRoute
    }
    '/_adminAuth/admin/blogs/$id': {
      id: '/_adminAuth/admin/blogs/$id'
      path: '/$id'
      fullPath: '/admin/blogs/$id'
      preLoaderRoute: typeof AdminAuthAdminBlogsIdRouteImport
      parentRoute: typeof AdminAuthAdminBlogsRoute
    }
  }
}

interface AdminAuthAdminBlogsRouteChildren {
  AdminAuthAdminBlogsIdRoute: typeof AdminAuthAdminBlogsIdRoute
  AdminAuthAdminBlogsNewRoute: typeof AdminAuthAdminBlogsNewRoute
}

const AdminAuthAdminBlogsRouteChildren: AdminAuthAdminBlogsRouteChildren = {
  AdminAuthAdminBlogsIdRoute: AdminAuthAdminBlogsIdRoute,
  AdminAuthAdminBlogsNewRoute: AdminAuthAdminBlogsNewRoute,
}

const AdminAuthAdminBlogsRouteWithChildren =
  AdminAuthAdminBlogsRoute._addFileChildren(AdminAuthAdminBlogsRouteChildren)

interface AdminAuthAdminCustomersRouteChildren {
  AdminAuthAdminCustomersIdRoute: typeof AdminAuthAdminCustomersIdRoute
}

const AdminAuthAdminCustomersRouteChildren: AdminAuthAdminCustomersRouteChildren =
  {
    AdminAuthAdminCustomersIdRoute: AdminAuthAdminCustomersIdRoute,
  }

const AdminAuthAdminCustomersRouteWithChildren =
  AdminAuthAdminCustomersRoute._addFileChildren(
    AdminAuthAdminCustomersRouteChildren,
  )

interface AdminAuthAdminEnquiriesRouteChildren {
  AdminAuthAdminEnquiriesIdRoute: typeof AdminAuthAdminEnquiriesIdRoute
  AdminAuthAdminEnquiriesNewRoute: typeof AdminAuthAdminEnquiriesNewRoute
}

const AdminAuthAdminEnquiriesRouteChildren: AdminAuthAdminEnquiriesRouteChildren =
  {
    AdminAuthAdminEnquiriesIdRoute: AdminAuthAdminEnquiriesIdRoute,
    AdminAuthAdminEnquiriesNewRoute: AdminAuthAdminEnquiriesNewRoute,
  }

const AdminAuthAdminEnquiriesRouteWithChildren =
  AdminAuthAdminEnquiriesRoute._addFileChildren(
    AdminAuthAdminEnquiriesRouteChildren,
  )

interface AdminAuthAdminOrdersRouteChildren {
  AdminAuthAdminOrdersIdRoute: typeof AdminAuthAdminOrdersIdRoute
}

const AdminAuthAdminOrdersRouteChildren: AdminAuthAdminOrdersRouteChildren = {
  AdminAuthAdminOrdersIdRoute: AdminAuthAdminOrdersIdRoute,
}

const AdminAuthAdminOrdersRouteWithChildren =
  AdminAuthAdminOrdersRoute._addFileChildren(AdminAuthAdminOrdersRouteChildren)

interface AdminAuthRouteChildren {
  AdminAuthAdminAnalyticsRoute: typeof AdminAuthAdminAnalyticsRoute
  AdminAuthAdminBlogsRoute: typeof AdminAuthAdminBlogsRouteWithChildren
  AdminAuthAdminCustomersRoute: typeof AdminAuthAdminCustomersRouteWithChildren
  AdminAuthAdminDashboardRoute: typeof AdminAuthAdminDashboardRoute
  AdminAuthAdminDeliveryZonesRoute: typeof AdminAuthAdminDeliveryZonesRoute
  AdminAuthAdminEnquiriesRoute: typeof AdminAuthAdminEnquiriesRouteWithChildren
  AdminAuthAdminIndustriesRoute: typeof AdminAuthAdminIndustriesRoute
  AdminAuthAdminOrdersRoute: typeof AdminAuthAdminOrdersRouteWithChildren
  AdminAuthAdminPaymentsRoute: typeof AdminAuthAdminPaymentsRoute
  AdminAuthAdminReviewsRoute: typeof AdminAuthAdminReviewsRoute
  AdminAuthAdminSettingsRoute: typeof AdminAuthAdminSettingsRoute
  AdminAuthAdminStaffRoute: typeof AdminAuthAdminStaffRoute
  AdminAuthAdminUsersRoute: typeof AdminAuthAdminUsersRoute
  AdminAuthAdminIndexRoute: typeof AdminAuthAdminIndexRoute
  AdminAuthAdminProductsIdRoute: typeof AdminAuthAdminProductsIdRoute
  AdminAuthAdminProductsNewRoute: typeof AdminAuthAdminProductsNewRoute
  AdminAuthAdminProductsIndexRoute: typeof AdminAuthAdminProductsIndexRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthAdminAnalyticsRoute: AdminAuthAdminAnalyticsRoute,
  AdminAuthAdminBlogsRoute: AdminAuthAdminBlogsRouteWithChildren,
  AdminAuthAdminCustomersRoute: AdminAuthAdminCustomersRouteWithChildren,
  AdminAuthAdminDashboardRoute: AdminAuthAdminDashboardRoute,
  AdminAuthAdminDeliveryZonesRoute: AdminAuthAdminDeliveryZonesRoute,
  AdminAuthAdminEnquiriesRoute: AdminAuthAdminEnquiriesRouteWithChildren,
  AdminAuthAdminIndustriesRoute: AdminAuthAdminIndustriesRoute,
  AdminAuthAdminOrdersRoute: AdminAuthAdminOrdersRouteWithChildren,
  AdminAuthAdminPaymentsRoute: AdminAuthAdminPaymentsRoute,
  AdminAuthAdminReviewsRoute: AdminAuthAdminReviewsRoute,
  AdminAuthAdminSettingsRoute: AdminAuthAdminSettingsRoute,
  AdminAuthAdminStaffRoute: AdminAuthAdminStaffRoute,
  AdminAuthAdminUsersRoute: AdminAuthAdminUsersRoute,
  AdminAuthAdminIndexRoute: AdminAuthAdminIndexRoute,
  AdminAuthAdminProductsIdRoute: AdminAuthAdminProductsIdRoute,
  AdminAuthAdminProductsNewRoute: AdminAuthAdminProductsNewRoute,
  AdminAuthAdminProductsIndexRoute: AdminAuthAdminProductsIndexRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutFailedRoute: typeof CheckoutFailedRoute
  CheckoutProcessingRoute: typeof CheckoutProcessingRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutFailedRoute: CheckoutFailedRoute,
  CheckoutProcessingRoute: CheckoutProcessingRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface AccountOrdersRouteChildren {
  AccountOrdersReferenceRoute: typeof AccountOrdersReferenceRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersReferenceRoute: AccountOrdersReferenceRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  EnterpriseQuoteRoute: EnterpriseQuoteRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  ProductsRoute: ProductsRouteWithChildren,
  StaffRoute: StaffRoute,
  AccountDashboardRoute: AccountDashboardRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountProfileRoute: AccountProfileRoute,
  AccountReferralsRoute: AccountReferralsRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountVerifyRoute: AccountVerifyRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  OrdersTrackRoute: OrdersTrackRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
