/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminAuthRouteImport } from './routes/_adminAuth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuthAdminStaffRouteImport } from './routes/_adminAuth.admin.staff'
import { Route as AdminAuthAdminSettingsRouteImport } from './routes/_adminAuth.admin.settings'
import { Route as AdminAuthAdminProductsRouteImport } from './routes/_adminAuth.admin.products'
import { Route as AdminAuthAdminEnquiriesRouteImport } from './routes/_adminAuth.admin.enquiries'
import { Route as AdminAuthAdminBlogsRouteImport } from './routes/_adminAuth.admin.blogs'
import { Route as AdminAuthAdminAnalyticsRouteImport } from './routes/_adminAuth.admin.analytics'
import { Route as AdminAuthAdminEnquiriesIdRouteImport } from './routes/_adminAuth.admin.enquiries.$id'
import { Route as AdminAuthAdminBlogsNewRouteImport } from './routes/_adminAuth.admin.blogs.new'
import { Route as AdminAuthAdminBlogsIdRouteImport } from './routes/_adminAuth.admin.blogs.$id'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/_adminAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthAdminStaffRoute = AdminAuthAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminSettingsRoute = AdminAuthAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminProductsRoute = AdminAuthAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminEnquiriesRoute = AdminAuthAdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminBlogsRoute = AdminAuthAdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminAnalyticsRoute = AdminAuthAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAdminEnquiriesIdRoute =
  AdminAuthAdminEnquiriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAuthAdminEnquiriesRoute,
  } as any)
const AdminAuthAdminBlogsNewRoute = AdminAuthAdminBlogsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminAuthAdminBlogsRoute,
} as any)
const AdminAuthAdminBlogsIdRoute = AdminAuthAdminBlogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAuthAdminBlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/analytics': typeof AdminAuthAdminAnalyticsRoute
  '/admin/blogs': typeof AdminAuthAdminBlogsRouteWithChildren
  '/admin/enquiries': typeof AdminAuthAdminEnquiriesRouteWithChildren
  '/admin/products': typeof AdminAuthAdminProductsRoute
  '/admin/settings': typeof AdminAuthAdminSettingsRoute
  '/admin/staff': typeof AdminAuthAdminStaffRoute
  '/admin/blogs/$id': typeof AdminAuthAdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminAuthAdminBlogsNewRoute
  '/admin/enquiries/$id': typeof AdminAuthAdminEnquiriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/analytics': typeof AdminAuthAdminAnalyticsRoute
  '/admin/blogs': typeof AdminAuthAdminBlogsRouteWithChildren
  '/admin/enquiries': typeof AdminAuthAdminEnquiriesRouteWithChildren
  '/admin/products': typeof AdminAuthAdminProductsRoute
  '/admin/settings': typeof AdminAuthAdminSettingsRoute
  '/admin/staff': typeof AdminAuthAdminStaffRoute
  '/admin/blogs/$id': typeof AdminAuthAdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminAuthAdminBlogsNewRoute
  '/admin/enquiries/$id': typeof AdminAuthAdminEnquiriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_adminAuth': typeof AdminAuthRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/_adminAuth/admin/analytics': typeof AdminAuthAdminAnalyticsRoute
  '/_adminAuth/admin/blogs': typeof AdminAuthAdminBlogsRouteWithChildren
  '/_adminAuth/admin/enquiries': typeof AdminAuthAdminEnquiriesRouteWithChildren
  '/_adminAuth/admin/products': typeof AdminAuthAdminProductsRoute
  '/_adminAuth/admin/settings': typeof AdminAuthAdminSettingsRoute
  '/_adminAuth/admin/staff': typeof AdminAuthAdminStaffRoute
  '/_adminAuth/admin/blogs/$id': typeof AdminAuthAdminBlogsIdRoute
  '/_adminAuth/admin/blogs/new': typeof AdminAuthAdminBlogsNewRoute
  '/_adminAuth/admin/enquiries/$id': typeof AdminAuthAdminEnquiriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/products'
    | '/admin/login'
    | '/blog/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/enquiries'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/enquiries/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/products'
    | '/admin/login'
    | '/blog/$slug'
    | '/products/$slug'
    | '/admin'
    | '/blog'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/enquiries'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/enquiries/$id'
  id:
    | '__root__'
    | '/'
    | '/_adminAuth'
    | '/about'
    | '/contact'
    | '/industries'
    | '/products'
    | '/admin/login'
    | '/blog/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/blog/'
    | '/_adminAuth/admin/analytics'
    | '/_adminAuth/admin/blogs'
    | '/_adminAuth/admin/enquiries'
    | '/_adminAuth/admin/products'
    | '/_adminAuth/admin/settings'
    | '/_adminAuth/admin/staff'
    | '/_adminAuth/admin/blogs/$id'
    | '/_adminAuth/admin/blogs/new'
    | '/_adminAuth/admin/enquiries/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminAuth': {
      id: '/_adminAuth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminAuth/admin/staff': {
      id: '/_adminAuth/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminAuthAdminStaffRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/settings': {
      id: '/_adminAuth/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthAdminSettingsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/products': {
      id: '/_adminAuth/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAuthAdminProductsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/enquiries': {
      id: '/_adminAuth/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminAuthAdminEnquiriesRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/blogs': {
      id: '/_adminAuth/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminAuthAdminBlogsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/analytics': {
      id: '/_adminAuth/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAuthAdminAnalyticsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_adminAuth/admin/enquiries/$id': {
      id: '/_adminAuth/admin/enquiries/$id'
      path: '/$id'
      fullPath: '/admin/enquiries/$id'
      preLoaderRoute: typeof AdminAuthAdminEnquiriesIdRouteImport
      parentRoute: typeof AdminAuthAdminEnquiriesRoute
    }
    '/_adminAuth/admin/blogs/new': {
      id: '/_adminAuth/admin/blogs/new'
      path: '/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminAuthAdminBlogsNewRouteImport
      parentRoute: typeof AdminAuthAdminBlogsRoute
    }
    '/_adminAuth/admin/blogs/$id': {
      id: '/_adminAuth/admin/blogs/$id'
      path: '/$id'
      fullPath: '/admin/blogs/$id'
      preLoaderRoute: typeof AdminAuthAdminBlogsIdRouteImport
      parentRoute: typeof AdminAuthAdminBlogsRoute
    }
  }
}

interface AdminAuthAdminBlogsRouteChildren {
  AdminAuthAdminBlogsIdRoute: typeof AdminAuthAdminBlogsIdRoute
  AdminAuthAdminBlogsNewRoute: typeof AdminAuthAdminBlogsNewRoute
}

const AdminAuthAdminBlogsRouteChildren: AdminAuthAdminBlogsRouteChildren = {
  AdminAuthAdminBlogsIdRoute: AdminAuthAdminBlogsIdRoute,
  AdminAuthAdminBlogsNewRoute: AdminAuthAdminBlogsNewRoute,
}

const AdminAuthAdminBlogsRouteWithChildren =
  AdminAuthAdminBlogsRoute._addFileChildren(AdminAuthAdminBlogsRouteChildren)

interface AdminAuthAdminEnquiriesRouteChildren {
  AdminAuthAdminEnquiriesIdRoute: typeof AdminAuthAdminEnquiriesIdRoute
}

const AdminAuthAdminEnquiriesRouteChildren: AdminAuthAdminEnquiriesRouteChildren =
  {
    AdminAuthAdminEnquiriesIdRoute: AdminAuthAdminEnquiriesIdRoute,
  }

const AdminAuthAdminEnquiriesRouteWithChildren =
  AdminAuthAdminEnquiriesRoute._addFileChildren(
    AdminAuthAdminEnquiriesRouteChildren,
  )

interface AdminAuthRouteChildren {
  AdminAuthAdminAnalyticsRoute: typeof AdminAuthAdminAnalyticsRoute
  AdminAuthAdminBlogsRoute: typeof AdminAuthAdminBlogsRouteWithChildren
  AdminAuthAdminEnquiriesRoute: typeof AdminAuthAdminEnquiriesRouteWithChildren
  AdminAuthAdminProductsRoute: typeof AdminAuthAdminProductsRoute
  AdminAuthAdminSettingsRoute: typeof AdminAuthAdminSettingsRoute
  AdminAuthAdminStaffRoute: typeof AdminAuthAdminStaffRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthAdminAnalyticsRoute: AdminAuthAdminAnalyticsRoute,
  AdminAuthAdminBlogsRoute: AdminAuthAdminBlogsRouteWithChildren,
  AdminAuthAdminEnquiriesRoute: AdminAuthAdminEnquiriesRouteWithChildren,
  AdminAuthAdminProductsRoute: AdminAuthAdminProductsRoute,
  AdminAuthAdminSettingsRoute: AdminAuthAdminSettingsRoute,
  AdminAuthAdminStaffRoute: AdminAuthAdminStaffRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  ProductsRoute: ProductsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
